spring:
  application:
    name: InfiniteChat-Agent
  data:
    redis:
      host: 134.175.219.78
      port: 59000
      password: e65K4t8w2
      ttl: 3600
      timeout: 30000


server:
  port: 10010
  servlet:
    context-path: /api


logging:
  level:
    dev.langchain4j.mcp: ERROR

pgvector:
  database: dp
  host: 134.175.219.78
  port : 54328
  user: root
  password: e65K4t7z1
  table: dp_embedding


langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: xxxxxxx
      embedding-model:
        model-name: text-embedding-v4
        api-key: xxxxxxx


bigmodel:
  api-key: xxxxxxxxxxxxxxxx


rag:
  docs-path: xxxxxxxx